platform :ios, "8.0"

use_frameworks!

pod "React",
  path: "node_modules/react-native",
  subspecs: %w{
    Core
    RCTAnimation
    RCTImage
    RCTText
    RCTNetwork
    RCTWebSocket
  }
pod "react-native-branch", path: "node_modules/react-native-branch"
pod "Branch-SDK", path: "node_modules/react-native-branch/ios"
pod "Yoga", path: "node_modules/react-native/ReactCommon/yoga"

target "WebViewExample"
project "WebViewExample", "Test-Debug" => :debug, "Test-Release" => :release
